### ISSUE TITLE
OS error 123

### ISSUE THREAD

**Issue by Cherman0** [Seefaaa/aseprite-dmi#28]
Script Version: v1.0.7 Windows, installed via dragging `aseprite-dmi-windows.aseprite-extension` into the aseprite window
Aseprite Version: v1.3.5-x64

What happened: When attempting to open goonstation/icons/obj/items/items.dmi (https://github.com/goonstation/goonstation/blob/master/icons/obj/items/items.dmi) with the plugin, results in the following error text and failed window: 

Failed to open the DMI file
The filename, directory name, or volume label syntax is incorrect. (os error 123)
![image](https://github.com/Seefaaa/aseprite-dmi/assets/99766513/45642f51-ad23-4115-8206-79abe822da4f)
C:\Users\myUserName\AppData\Roaming\Aseprite\extensions\asprite-dmi\scripts\editor\rendering:lua:178: attempt to index a nil value (field 'dmi')
![image](https://github.com/Seefaaa/aseprite-dmi/assets/99766513/4130c2d9-0604-447d-a6d2-a90b5d58e1c7)
Window displays "Loading..." until it is clicked, then displays nothing.
![image](https://github.com/Seefaaa/aseprite-dmi/assets/99766513/899bfb2b-0e7e-47c5-903b-35f68e088c0a)

Other `.dmi` files in the codebase open without issue.

**Comment by Seefaaa** [comment]
This extensions caches states inside your temp directory with their respective names. So It happens beacause there is a state named "???" which can not be used to name a file in Windows.
